name: Build and Install UKUI Kernel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5-dev libssl-dev libelf-dev build-essential \
            flex bison openssl bc zlib1g-dev git make gcc

      - name: Download Kernel Source
        run: |
          sudo wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.22.tar.xz
          tar -xf linux-6.6.22.tar.xz
          cd linux-6.6.22

      - name: Configure Kernel
        run: |
          cd linux-6.6.22
          cp /boot/config-$(uname -r) .config
          yes "" | make oldconfig
          make menuconfig

      - name: Compile Kernel
        run: |
          cd linux-6.6.22
          make -j$(nproc)
          sudo make modules_install
          sudo make install

      - name: Update GRUB
        run: |
          sudo update-initramfs -c -k 6.6.22
          sudo update-grub

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-deb-packages
          path: linux-6.6.22/debian/
