name: Build and Install UKUI Kernel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5-dev libssl-dev libelf-dev build-essential \
            flex bison openssl bc zlib1g-dev git make gcc
          sudo apt install fakeroot dwarves

      - name: Download Kernel Source
        run: |
          sudo wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.22.tar.xz
          tar -xf linux-6.6.22.tar.xz
          cd linux-6.6.22

      - name: Configure Kernel
        run: |
          cd linux-6.6.22
          sudo make localmodconfig
          sudo scripts/config --disable SYSTEM_TRUSTED_KEYS
          sudo scripts/config --disable SYSTEM_REVOCATION_KEYS
          sudo scripts/config --set-str CONFIG_SYSTEM_TRUSTED_KEYS ""
          sudo scripts/config --set-str CONFIG_SYSTEM_REVOCATION_KEYS ""

      - name: Compile Kernel
        run: |
          cd linux-6.6.22
          sudo fakeroot make -j4
          sudo echo $?

      - name: Install Kernel
        run: |
          sudo make modules_install
          sudo make install

      - name: Check for correctness
        run: |
          uname -rs
